package de.scisertec.event.domain.model.feature;

public enum EventFeatureType {
    PARTICIPANT_STATUS, DINNER, DINNER_COMBO, SELECTION, DISCLAIMER, REGISTRATION, INDEX, CANCELLATION, BANK_TRANSFER, PAYPAL,
    PAYMENT_GENERAL, MAIL_GENERAL, MAIL_REGISTRATION, MAIL_PAYMENT, MAIL_CREDIT, MAIL_PAYMENT_COMPLETE, PAPER_SESSION, PAPER_SUBMISSION_TYPE,
    PAPER_REFERENCE, PAPER_GENERAL, SUBMISSION, PAPER_ATTACHMENT, REVIEW_GENERAL, REVIEW_RECOMMENDATION, REVIEW_RATING
}
